### PR TITLE
RoleModule alias updates (super important)

### PR DESCRIPTION
**Pull request by ssbmars**
added more emojis that you can toggle atb/atm roles with

### CODE REVIEW

**Comment by MegaMasterX** [comment]
I have a small concern about merging this in and using server-based emojis versus unicode ones.  The emotes on the server change occasionally and if, somehow, in the future, administration decides to cycle out an emote or a new admin who doesn't know the command removes the emote, this could cause the bot to provide errors, requiring rework. 

I'm inclined not to allow this change given the nature of server-based emotes. I won't close this request, but will wait for further feedback and discussion before declining the change.

**Comment by ssbmars** [comment]
this poses a good question, does it ignore invalid emoji IDs or does it explode if you give it a fake ID? If the worst case scenario for deleting an emoji is that the emoji can no longer be used as an alias, then it's not a problem. If something worse happens then we do have a problem because there is already an alias for at least one custom emoji.  

Could you spin up a test instance of qbot and throw some emoji scenarios at it to see how it responds

**Comment by ssbmars** [comment]
Also I've committed a few real bugfixes in this branch. Please check the new commits for obvious syntax errors, I'm not even sure what language I was writing in lmao

**Comment by MegaMasterX** [comment]
I created a test instance for the bot in a sandbox and invalid emotes will simply not trigger the command, so the only real reason not to do this is future code readability. Future developers might not be able to reference certain emotes.

For commit 50c3cbec,  I suggest using a **const string** for responses _outside_ of a method for this rather than declaring a variable within the method for a stock response.  It may seem nitpicky but this is best-practice for something like this.

Once you correct this, I'm cool with merging this in.

**Comment by ssbmars** [comment]
Well I think I got the scope right. You mentioned code readability with the ridiculously long emoji IDs getting used as aliases. Can we pass a variable as an alias string? If so it may be a better idea to define emoji IDs as const strings upfront so we can use vars while listing the aliases.

**Comment by MegaMasterX** [comment]
a60a05a is correct and looks good.

The commit 2a9cd2c is actually unnecessary, doing camelCase is appropriate for a private variable like this, but its cool to keep it as is. 

Emoji aliases won't be able to be used like this as I don't believe you can use variables within preprocessors like this, so a884c9b will need to be reverted and then we can merge this in.  

I'm sorry again if this seems nitpicky! :(

**Comment by ssbmars** [comment]
alias variables reverted, turned another string into a constant and double checked that this type of string parkour is legal in C#

**Comment by ssbmars** [comment]
I gave it another look over, pretty sure I caught all the syntax errors. No additional changes come to mind for me

**Comment by MegaMasterX** [comment]
Marking this as In Test, I'll pull the changes tonight, test them on the Beta branch, and update when testing is complete. Thank you Mars! More to come.

**Comment by MegaMasterX** [comment]
This works. @Zulleyy3 could you pull this and update the live ColonelBot instance?  

Thank you in advance!

**Pull request merged**
